/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppPortfolioRouteImport } from './routes/_app.portfolio'
import { Route as AppMoodMapRouteImport } from './routes/_app.mood-map'
import { Route as AppFlavoursRouteImport } from './routes/_app.flavours'
import { Route as AppEfficiencyRouteImport } from './routes/_app.efficiency'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCitiesRouteImport } from './routes/_app.cities'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppMoodMapRoute = AppMoodMapRouteImport.update({
  id: '/mood-map',
  path: '/mood-map',
  getParentRoute: () => AppRoute,
} as any)
const AppFlavoursRoute = AppFlavoursRouteImport.update({
  id: '/flavours',
  path: '/flavours',
  getParentRoute: () => AppRoute,
} as any)
const AppEfficiencyRoute = AppEfficiencyRouteImport.update({
  id: '/efficiency',
  path: '/efficiency',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCitiesRoute = AppCitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cities': typeof AppCitiesRoute
  '/dashboard': typeof AppDashboardRoute
  '/efficiency': typeof AppEfficiencyRoute
  '/flavours': typeof AppFlavoursRoute
  '/mood-map': typeof AppMoodMapRoute
  '/portfolio': typeof AppPortfolioRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cities': typeof AppCitiesRoute
  '/dashboard': typeof AppDashboardRoute
  '/efficiency': typeof AppEfficiencyRoute
  '/flavours': typeof AppFlavoursRoute
  '/mood-map': typeof AppMoodMapRoute
  '/portfolio': typeof AppPortfolioRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/cities': typeof AppCitiesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/efficiency': typeof AppEfficiencyRoute
  '/_app/flavours': typeof AppFlavoursRoute
  '/_app/mood-map': typeof AppMoodMapRoute
  '/_app/portfolio': typeof AppPortfolioRoute
  '/_app/settings': typeof AppSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cities'
    | '/dashboard'
    | '/efficiency'
    | '/flavours'
    | '/mood-map'
    | '/portfolio'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cities'
    | '/dashboard'
    | '/efficiency'
    | '/flavours'
    | '/mood-map'
    | '/portfolio'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/cities'
    | '/_app/dashboard'
    | '/_app/efficiency'
    | '/_app/flavours'
    | '/_app/mood-map'
    | '/_app/portfolio'
    | '/_app/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolio': {
      id: '/_app/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mood-map': {
      id: '/_app/mood-map'
      path: '/mood-map'
      fullPath: '/mood-map'
      preLoaderRoute: typeof AppMoodMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flavours': {
      id: '/_app/flavours'
      path: '/flavours'
      fullPath: '/flavours'
      preLoaderRoute: typeof AppFlavoursRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/efficiency': {
      id: '/_app/efficiency'
      path: '/efficiency'
      fullPath: '/efficiency'
      preLoaderRoute: typeof AppEfficiencyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cities': {
      id: '/_app/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof AppCitiesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCitiesRoute: typeof AppCitiesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEfficiencyRoute: typeof AppEfficiencyRoute
  AppFlavoursRoute: typeof AppFlavoursRoute
  AppMoodMapRoute: typeof AppMoodMapRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCitiesRoute: AppCitiesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEfficiencyRoute: AppEfficiencyRoute,
  AppFlavoursRoute: AppFlavoursRoute,
  AppMoodMapRoute: AppMoodMapRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
